<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="US107559WIN" failures="1" tests="1" name="Add Account" time="75.174" errors="0" timestamp="2021-08-03T23:25:06 EEST">
  <testcase classname="com.bottomline.tests.AccountCRUD" name="Add" time="71.322">
    <failure type="java.lang.AssertionError" message="expected [Successfully Added] but found [This record already exists.]">
      <![CDATA[java.lang.AssertionError: expected [Successfully Added] but found [This record already exists.]
at com.bottomline.tests.AccountCRUD.Add(AccountCRUD.java:34)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- Add -->
</testsuite> <!-- Add Account -->
